name: RegionRegenerator
version: ${project.version}
main: deadlight.regionregenerator.Main
authors: [Dead_Light]
description: Add as many regions as you want and make the region ores regenerate after being broken
depend: [WorldGuard]
commands:
  regenerativeRegions:
    description: main command for RegionRegenerator plugin.
    aliases:
      - rr